name: CI

on:
  push:
    branches:
      - 'auto-cadence-upgrade/**'
      - staging
      - trying
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master*
      - 'auto-cadence-upgrade/**'
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'
  merge_group:
    branches:
      - master

env:
  GO_VERSION: "1.23"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build-linter:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "1.23"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Cache custom linter binary
        id: cache-linter
        uses: actions/cache@v3
        with:
          # key should change whenever your linter code or Go version changes
          key: custom-linter-${{ env.GO_VERSION }}-${{ runner.os }}-${{ hashFiles('.custom-gcl.yml', 'tools/structwrite/**') }}
          path: tools/custom-gcl

      - name: Install golangci-lint
        if: steps.cache-linter.outputs.cache-hit != 'true'
        uses: golangci/golangci-lint-action@v6
        continue-on-error: true
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.63
          args: "--no-config --disable-all"
      - name: Build custom linter
        if: steps.cache-linter.outputs.cache-hit != 'true'
        run: |
          golangci-lint custom

      - name: Upload linter binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-gcl
          path: tools/custom-gcl


  lint:
    name: Lint
    needs: build-linter
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dir: [ ./, ./integration/, ./insecure/ ]

    steps:
      - name: Download custom linter
        uses: actions/download-artifact@v4
        with:
          name: custom-gcl
          path: ./tools/
      # must have expected binary name for use in default gcl action
      - name: Rename custom linter binary to canonical
        run: mv ./tools/custom-gcl ./tools/golangci-lint
      - name: DEBUG print tools
        run: ls tools/*
      - name: Make lint binary executable
        run: chmod +x ./tools/golangci-lint
      - name: Add lint binary to path
        run: echo "$(pwd)/tools" >> $GITHUB_PATH
      - name: DEBUG print path
        run: echo "$PATH --- $(pwd)"
      - name: DEBUG which
        run: which golangci-lint
      - name: DEBUG lint run test
        run: golangci-lint version
        continue-on-error: true
      - name: DEBUG print tools
        run: ls tools/*

      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Run go generate
        run: go generate ./...
        working-directory: ${{ matrix.dir }}

      - name: DEBUG print path
        run: echo "$PATH --- $(pwd)"
      - name: DEBUG which
        run: which golangci-lint
      - name: DEBUG lint run test
        run: golangci-lint version
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: 'none' # looks for binary in path rather than downloading
          args: "-v"
          working-directory: ${{ matrix.dir }}
